[package]
name = "nsbox"
version = "0.1.0"
edition = "2024"
description = "A lightweight sandbox runner for Linux"
readme = "README.md"
repository = "https://github.com/OldUser101/nsbox"
license = "MIT OR Apache-2.0"

[dependencies]
